version: '3'
services:
  api:
    container_name: api_b
    restart: always
    build: .
    ports:
      - '3001:3001'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'


